import streamlit as st
from utils import generate_image_with_diffusers
options = st.sidebar.selectbox("Select your choice", ["Home","Diffusion Model","DALL-E"])

if options == "Home":
    st.title("Text to Image Generation App.")
    with st.expander("About the App"):
        st.write("This is an application to create images according to the prompt given!!")

elif options == "Diffusion Model":
    st.subheader("Image generation using Huggingface Diffusers")
    input_prompt = st.text_input("Enter your text prompt")
    if input_prompt is not None:
        if st.button("Generate Image"):
            image_output = generate_image_with_diffusers(input_prompt)
            st.info("Generating image.....")
            st.success("Image Generated Successfully")
            st.image(image_output, caption="Generated by Huggingface Diffusers")

elif options == "DALL-E":
    st.subheader("Image generation using DALL-E")
    input_text = st.text_input("Enter the prompt..")
    st.button("Generate")

